name: Run actionlint

inputs:
  args:
    required: false
    default: "-color"

runs:
  using: "composite"
  steps:
    - uses: docker://rhysd/actionlint:1.7.7@sha256:887a259a5a534f3c4f36cb02dca341673c6089431057242cdc931e9f133147e9
      with:
        args: ${{ inputs.args }}
