name: Run actionlint

inputs:
  args:
    required: false
    default: "-color"

runs:
  using: "composite"
  steps:
    - uses: docker://rhysd/actionlint:1.7.9@sha256:a0383f60d92601e2694e24b24d37df7b6a40bed7cedbc447611c50009bf02d94
      with:
        args: ${{ inputs.args }}
